### ISSUE TITLE
create css variables for colors properties in ejs

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#10]
### What would you like to be added?

color is applied to different constraints as inline style, make them variables in an external stylesheet
![image](https://github.com/Bhanu-code/db-drawer/assets/77599001/dfb230ad-597c-44bd-8074-5f7a584ee2d2)

### Why is this needed?

for code organisation

**Comment by DhayanandhS** [comment]
I would like to contribute to this issue. Under GSSoc'24 as a contributor.

**Comment by Bhanu-code** [comment]
@DhayanandhS you're welcomed. this issue can be resolved only after the issue #7 is completed. You can ask to co-auther issue #7 with the current assignee. Please go through README.md, Learn.md and CODE_OF_CONDUCT.md. feel free to ask question in discord community.

**Comment by DhayanandhS** [comment]
Can you assign me this issue? eagerly looking forward to contribute to this issue.

**Comment by PRATHAMU200** [comment]
I can work on this project as soons as possible and do it early i guess this don't take much time could you assign this to me?

**Comment by Bhanu-code** [comment]
@PRATHAMU200  this issue is already assigned. You can ask @DhayanandhS  to co-author or checkout other issues. you can raise new issues or come up with new ideas also.

**Comment by PRATHAMU200** [comment]
@Bhanu-code Is their any timelimit when the Assignees not able to complete the task? and please tell what is that timelimit when the you will reassigne when the issue will not be solved?

**Comment by Bhanu-code** [comment]
> @Bhanu-code Is their any timelimit when the Assignees not able to complete the task? and please tell what is that timelimit when the you will reassigne when the issue will not be solved?

not as such anytime time limit. just make sure you don't stale the issue. if you are getting problems ask and try to reach out the fellow contributors to get help. join the discord server from README for better discussions.

**Comment by Bhanu-code** [comment]
@DhayanandhS you can now start working on this issue as external stylesheets are added.

**Comment by DhayanandhS** [comment]
okey. i'll start working on it.

**Comment by DhayanandhS** [comment]
Is this okey?
![Screenshot 2024-05-15 104147](https://github.com/Bhanu-code/db-drawer/assets/112493275/5e9ca7ae-bb7f-483a-ab05-d6fa5ebe55b5)
![Screenshot 2024-05-15 104213](https://github.com/Bhanu-code/db-drawer/assets/112493275/08f8e110-2390-404d-8cc8-fa69d03d509f)
![Screenshot 2024-05-15 104243](https://github.com/Bhanu-code/db-drawer/assets/112493275/ce118405-6fa4-44c5-9a3d-44b0a837c2d2)

**Comment by Bhanu-code** [comment]
@DhayanandhS looks good! raise the PR.
