### ISSUE TITLE
[Feature]: <Add icon based github repository link in view files in ejs>

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#12]
### Description

Add icon based link to github repository of the project in each ejs file inside of views

### Suggested Solution

Use free icons to achieve this.

**Comment by haard18** [comment]
I want to Contribute to this, Please Assign it to me and if convenient label the issue under GSSOC'24

**Comment by Bhanu-code** [comment]
@haard18 go ahead!
