### ISSUE TITLE
[Feature]: <Add support for TypeORM>

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#23]
### Description

Current version of the project only works for mongoose and sequelize ORM. add support for TypeORM also.

### Suggested Solution

Explore TypeORM. Checkout docs for TypeORM.

**Comment by cu8code** [comment]
Hi, I would like to work on this! Will be great if you could assign me this one!
I am thinking we need to add support for Type-ORM inside server folder! Then add support for the data visualization inside the view folder!

**Comment by cu8code** [comment]
@Bhanu-code I will drop this issue did not find any suitable solution! will move to a diffrent issue

**Comment by haard18** [comment]
I can pick it up!
