### ISSUE TITLE
[Feature]: <Add support for Prisma ORM also>

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#24]
### Description

Current version of the project does not support Prisma ORM. Add support for Prisma ORM.

### Suggested Solution

Checkout Prisma docs.

**Comment by haard18** [comment]
Assign me the issue, I want to contribute under GSSOC'24 so please label it if You're assigning

**Comment by haard18** [comment]
I can generate a Database for Prisma ORMs and can try to implement the arrows to show the relations between tables of any database, this are HighLevel checkpoints, can explain in further details @Bhanu-code

**Comment by Bhanu-code** [comment]
@haard18 Sure! join the discord for further discussions

**Comment by haard18** [comment]
Thankyou, where can i find the Discord Link?
