### ISSUE TITLE
Draw digital architechture of the project

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#26]
### What would you like to be added?

Transform the below drawn architechture digitally with good colours. Add it in Learn.md under project architechture section.
![db-draewr architechture](https://github.com/Bhanu-code/db-drawer/assets/77599001/76aa878a-a0d9-4a7c-b187-98e6b298aad2)

### Why is this needed?

This will give new contributors good understanding of control flow in the project.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Bhanu-code** [comment]
@suhanipaliwal  any updates?

**Comment by suhanipaliwal** [comment]
I'm working on it. Actually my exams are going on right now so it's taking a bit longer time to complete. Really sorry for that.
