### ISSUE TITLE
make servers port dynamic

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#27]
### What would you like to be added?

servers has hard coded port number i.e 3001. Users can't run sqlz and mongo servers at same because both specified same port number. allow users to run servers parallely.

![image](https://github.com/Bhanu-code/db-drawer/assets/77599001/6d7b066b-5724-4e01-8de6-42dde6c4c3f2)

![image (1)](https://github.com/Bhanu-code/db-drawer/assets/77599001/d33807a4-ae23-4c0b-b08c-495ca4ef69e4)

### Why is this needed?

To improve user experience.

**Comment by Raushan0303** [comment]
Assign it to me i will do that

**Comment by Bhanu-code** [comment]
@Raushan0303 suggest some ideas on discord, how will you make servers run parallely.

**Comment by Bhanu-code** [comment]
@Raushan0303 do it if you want to do.

**Comment by juniorcoder02** [comment]
hi project admin @Bhanu-code  i'm participant in Gssoc'24 and i am thrilled to be contributing to db-drawer. after reviewing the open issues, i'm particularly interested in make server port dynamic as it aligns well with my skills and interests.                                                                                                                                       Could you please assign this issue to me? I'm eager to dive in and make a meaningful contribution to the project.

**Comment by Bhanu-code** [comment]
@Raushan0303 is assigned for the issue. So, @juniorcoder02 You can ask @Raushan0303 to co-auther or can chekout other issues also.

**Comment by Bhanu-code** [comment]
issues are assigned on first come first serve basis. if @Raushan0303 will not able for resolve this issue, next comers will be assigned.

**Comment by haard18** [comment]
Any updates here @Bhanu-code

**Comment by Bhanu-code** [comment]
@Raushan0303 any updates?
