### ISSUE TITLE
[Bug] <Visualization server scrolls automatically>

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

visualization servers scrolls automatically because of "settimeout()". prevent this behaviour of auto scrolling

### Expected Behaviour

It should  not scroll automatically

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by haard18** [comment]
I would like to contribute to this
