### ISSUE TITLE
[Bug] Updating Readme document 

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Bhanu-code/db-drawer#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by SuhainaFathimaM** [comment]
@Bhanu-code I would like to work this task.. 
Please assign me this task under GSSoC'24  label..

**Comment by aasthakourav20** [comment]
> @SuhainaFathimaM what update you want to do in README?

Hey @Bhanu-code l , A Readme file plays an important role in User/Contributor convenience  .It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers.
Let's create a more descriptive , attention seeking README file including all guidelines .

Kindly assign this issue to me under GSSoC'24 .

**Comment by Bhanu-code** [comment]
@aasthakourav20 I think, we have all the things included  in  REAME.md, Learn.md, CODE_OF_CONDUCT, etc. Please go through README.md, Learn.md
