### ISSUE TITLE
[Bug] <External styles are not applying to the sqlz.ejs>

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

External styles failed to apply on sqlz.ejs

### Expected Behaviour

All styles should reflect on sqlz.ejs

### Environment

```markdown
- OS:Linux mint 21
- Node:
- npm:
```

**Comment by anglerfishlyy** [comment]
can you assign me this issue ? i can work on it.
