### ISSUE TITLE
[Feature]: Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Bhanu-code/db-drawer#47]
## Security Feature
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

### Suggested Solution

I'll implement a feature that will not allow such emails for login or register.
Assign me this work under GSSoC24, I will implement it.

**Comment by Bhanu-code** [comment]
@pankaj-bind our application does not need an authentication system. it is a cli tool.

**Comment by pankaj-bind** [comment]
> @pankaj-bind our application does not need an authentication system. it is a cli tool and If I am unable understand what you want to say. Join our discord server and ping me.

It is not only work for authentication. It will allow only those emails which are genuine.
