### ISSUE TITLE
[Bug] <Add Shebang to index.js>

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

By somehow shebang has been removed from index.js. This will break the functionality to run as cli.

### Expected Behaviour

Add shebang to index.js

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by haard18** [comment]
Assign me i have fixed this already 
added 
```
#!/usr/bin/env node
```

**Comment by haard18** [comment]
@Bhanu-code
