### ISSUE TITLE
[Bug] <Remove console.log of models while running mongo.js>

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

![image](https://github.com/Bhanu-code/db-drawer/assets/77599001/1eff2670-68bb-4844-b12d-8ac7e1792264)

remove model console log from terminal

### Expected Behaviour

terminal should not contain any log related to model architechture

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by haard18** [comment]
I will do it

**Comment by haard18** [comment]
@Bhanu-code
