### ISSUE TITLE
Command Discrepancy: Sequelize vs. Mongoose in db-drawer Tool

### ISSUE THREAD

**Issue by kvdevlopment** [Bhanu-code/db-drawer#54]
**Description:**

While using the db-drawer tool, I noticed a discrepancy in the commands provided for running the tool with Sequelize and Mongoose.

For Sequelize, the command is:
```npx db-drawer s```

However, for Mongoose, the command is:
npx db-draw m
The inconsistency in the commands could lead to confusion for users, especially those new to the tool. To improve clarity and consistency, I suggest aligning the commands for both Sequelize and Mongoose usage.

**Proposed Solution:**

Update the command for Mongoose usage to match the format used for Sequelize, like so:

```npx db-drawer m```
This adjustment will enhance user experience and ensure consistency across the tool's functionality.

**You can refer below:**
![2024-05-16 00_27_02-](https://github.com/Bhanu-code/db-drawer/assets/109462746/0bd79b48-f11f-4cc9-bb01-e93d3f8a6837)

**Comment by kvdevlopment** [comment]
Hello @Bhanu-code 

Sir, Please assign me this issue.

**Comment by Bhanu-code** [comment]
@kvdevlopment go ahead update the commands and docs as well
