### ISSUE TITLE
[Feature]: Workflow for auto commenting on PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [Bhanu-code/db-drawer#63]
### Description

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

### Suggested Solution

To enhance our communication and acknowledgment process, we're implementing an auto-commenting feature for specific events within our project repository. This feature will automatically generate comments under the following circumstances:
PR Merged: Upon the successful merging of a pull request (PR), an auto-comment will be added to the corresponding issue, indicating that the PR has been merged and expressing gratitude to the contributor for their valuable contribution.

**Comment by Asymtode712** [comment]
@Bhanu-code please assign me this issue under gssoc'24

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Asymtode712** [comment]
@suhanipaliwal I have already authored this issue please work on some other issue
Thank you!
