### ISSUE TITLE
[Feature]: Workflow for closing old PRs

### ISSUE THREAD

**Issue by Asymtode712** [Bhanu-code/db-drawer#65]
### Description

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Suggested Solution

Implement a workflow that automatically closes old PRs based on predefined criteria, such as their last update timestamp. By regularly closing PRs that have not been updated within a certain timeframe, the repository can stay organized, and contributors can focus on active and relevant PRs.

**Comment by Asymtode712** [comment]
@Bhanu-code please assign me this issue under gssoc'24

**Comment by Asymtode712** [comment]
@Bhanu-code please assign me this issue under gssoc'24

**Comment by Bhanu-code** [comment]
@Asymtode712 will you be able to explain me about issue and the solution in team meeting?
