### ISSUE TITLE
migrate the internal styles to external stylesheets

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#7]
In the ejs files inside of view folder, styles are mentioned as internal style in an <style> tag. Create external stylesheet files and copy paste the styles from <style> tag. Make sure to link stylesheets and validate the styles.

![image](https://github.com/Bhanu-code/db-drawer/assets/77599001/3d53ad2d-1157-4937-bb23-73ab7b6b288b)

**Comment by zenessis** [comment]
Can I handle this? is it fine if I put all the external stylesheets into a specific folder?

**Comment by Bhanu-code** [comment]
@zenessis  yes it is fine but make sure they applys properly to ejs view files. I suggest go through README, watch the quick glimpse video, join our discord channel, ask questions in the discord server. Soon I will make a demonstration video explaining everything about the project. I suggest you wait till that.

**Comment by zenessis** [comment]
aight! I'll remember and start contributing after the video. Thanks!

**Comment by PRATHAMU200** [comment]
I can work on this project, could you assign it to me, so that i can work right now on this. I guess this doesn't take much time??

**Comment by Bhanu-code** [comment]
@PRATHAMU200 you can ask @zenessis to co-author or check other potential issues.

**Comment by zenessis** [comment]
@Bhanu-code I'll finish it today. Thanks for having me and @PRATHAMU200  Sorry! I'll do it.

**Comment by Bhanu-code** [comment]
Don't be sorry guys! @PRATHAMU200  and @zenessis  you both can work on this, if you guys want. And don't rush to contribute. Take time to make value PRs.
