### ISSUE TITLE
[Other] <Update the documentation>

### ISSUE THREAD

**Issue by Bhanu-code** [Bhanu-code/db-drawer#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem or Suggestment

As the project has now typeorm and prisma support as well, we need to update the documentation as well.

**Comment by kosuri-indu** [comment]
@Bhanu-code 
I want to work on this, by updation in documentation, do you mean changes need to be made in Learn.md and Readme.md?

**Comment by Bhanu-code** [comment]
@kosuri-indu you need to update README.md with respective commands for the projects. I suggest you joining group meetings in discord server where we will be discussing about neccessary changes to done.
