### ISSUE TITLE
Implement Export to PDF/PNG Feature

### ISSUE THREAD

**Issue by sanskriti-lal** [Bhanu-code/db-drawer#75]
### Description

This feature adds an option in the db-drawer tool that allows users to export the visualized database schema as a PDF or PNG file. This enhancement will enable users to create static, shareable representations of their database structure.

### Suggested Solution

The proposed solution involves adding "Export as PDF" and "Export as PNG" buttons to the db-drawer interface, allowing users to easily export the visualized database schema. The tool will then automatically prompt the user to download the generated file, named appropriately. This feature will enhance the usability of db-drawer by enabling users to create and share static representations of their database structures for documentation and presentations.

### Additional Context

I'm a GSSoC'24 contributor with a strong background in web development and experience working with libraries such as html2canvas and jsPDF and I want to work on this feature addition. So can you please assign this work to me @Bhanu-code

**Comment by Bhanu-code** [comment]
@sanskriti-lal cool!, sounds great. I am assigning you the issue. make sure to go through CODE_OF_CONDUCT and README.md. For any issue, ask on the gssoc discord server.

**Comment by sanskriti-lal** [comment]
Thank you @Bhanu-code  for assigning me this work. I'll start working on it. Also one little request, can you please give it a level2 tag.

**Comment by Bhanu-code** [comment]
@sanskriti-lal  we have our guideliness by GSSoC  for labeling. So, we have to label accordingly.

**Comment by sanskriti-lal** [comment]
ok cool! Also I've made a PR can you please look into it @Bhanu-code
