### ISSUE TITLE
Feature🌟 : Add "Scroll to Top" Button

### ISSUE THREAD

**Issue by aslams2020** [Bhanu-code/db-drawer#78]
### Description

Hey @Bhanu-code,
Here is the feature i want to suggest and implement -

I would like to implement a "Scroll to Top" button that appears when the user scrolls down the page. This button should be prominently displayed and easy to click, allowing users to quickly return to the top of the page with a single click.
The button can be styled to fit the design of the website and could be positioned at the bottom right corner of the viewport.

Overall, the "Scroll to Top" button is a small yet impactful addition that contributes to a seamless and enjoyable browsing experience for your website visitors.

### Suggested Solution

Add an anchor element with appropriate classes and IDs in HTML, apply CSS styles for button appearance, and use JavaScript to handle scrolling events and scroll functionality to the top of the page.

### Additional Context

**Attachments**
This is where we will add the "Scroll to top" button to improve user experience to be more convienient.

![image](https://github.com/Bhanu-code/db-drawer/assets/131389695/cca6e77f-e2ca-4b63-a359-8901450e3c1f)

@Bhanu-code, Could you please assign me this issue under GSSOC'24?
I will be happy to contribute to your project.

**Comment by aslams2020** [comment]
@Bhanu-code

**Comment by Bhanu-code** [comment]
@aslams2020 the page you have refered is of npm registry. we can't modify that and I don't think we need this now.
